influx:
  uri: "http://localhost:8086"
  org: "eventline"
  bucket: "main"
  token: "admin"

encryption_key: "kDWhsf6HuLOr/3i0rTfOMaFhAWDwfjjgOOKG+TdodyE="

connectors:
  github:
    enabled: true
    webhook_secret: "dd09de5ee4b026def599c3e6a0cf8f4a"

notifications:
  smtp_server:
    address: "localhost:1025"
  subject_prefix: "[eventline/dev] "
