#!/bin/sh

set -eu

root=$(realpath $(dirname $0)/..)

schema=eventline
date=$(date -u "+%Y%m%dT%H%M%SZ")

schema_dir=$root/data/pg/schemas/$schema
mkdir -p $schema_dir

schema_path=$schema_dir/$date.sql

touch $schema_path
echo $schema_path
