== Deployment and configuration

=== Requirements

Eventline is written in Go and distributed as a statically linked executable
for various platforms.

The following platforms are officially supported for production:

- Linux x86_64.
- FreeBSD x86_64.

Binaries are also released on a best effort basis for the following platforms:

- Mac OS x86_64.
- Mac OS arm64 (M1).

Eventline uses a https://www.postgresql.org[PostgreSQL database] version 14 or
higher; the https://www.postgresql.org/docs/current/pgcrypto.html[pgcrypto]
extension must be installed. It does not require local filesystem storage.

Eventline can also send metrics to an https://www.influxdata.com[InfluxDB]
server.

=== Installation

==== Binary tarballs

Eventline is released primarily as a set of binary tarballs. Each tarball
contains everything required to run the program:

* Both the `eventline` and the `evcli` executables.
* The Eventline license.
* The `data` directory containing web assets, database migrations and template
  files.
* This handbook both as a PDF file and a HTML file with associated images.

While you can run Eventline directly from the tarball directory, you will want
something more practical for production. As such, binary tarballs are
generally only used by people building packages or images themselves.

==== FreeBSD package

_Coming soon_.

==== Ubuntu package

_Coming soon_.

==== Archlinux package

_Coming soon_.

==== Docker image

The `exograd/eventline` image is available on
https://hub.docker.com[DockerHub]. Versioning is the same as Eventline: for
example, Eventline 0.9.0 is available with `exograd/eventline:0.9.0`.

While the `latest` tag usually points to the latest available release, it is
strongly recommended not to use it and to always use a specific version tag to
avoid unexpected updates.

===== Configuration

When running in this Docker image, Eventline can be configured two ways.

One way is to mount a configuration file of your choice in the container at
`/etc/eventline/eventline.yaml`. This gives you maximum flexibility.

An over way is to rely on the embedded configuration file which uses
environment variables for configuration. The following variables are
available:

`EVENTLINE_WEB_HTTP_SERVER_URI` (optional, default to `localhost:8087`) :: The
value to use for the `web_http_server_uri` setting.

`EVENTLINE_PG_URI` (optional) :: The URI of the PostgreSQL server. The default
value is `postgres://eventline:eventline@localhost:5432/eventline`.

`EVENTLINE_ENCRYPTION_KEY` :: The value to use for the `encryption_key`
setting.

`EVENTLINE_CONNECTORS_GITHUB_WEBHOOK_SECRET` :: The value of the
`webhook_secret` setting for the `github` connector. Setting this variable
automatically enable the connector.

`EVENTLINE_MAX_PARALLEL_JOB_EXECUTIONS` :: The value to use for the
`max_parallel_job_executions` setting.

`EVENTLINE_JOB_EXECUTION_RETENTION` :: The value to use for the
`job_execution_retention` setting.

`EVENTLINE_SESSION_RETENTION` :: The value to use for the `session_retention`
setting.

`EVENTLINE_NOTIFICATIONS_SMTP_SERVER_ADDRESS` (optional, default to `localhost:25`) ::
The address of the SMTP server to use for notifications.

`EVENTLINE_NOTIFICATIONS_SMPT_SERVER_USERNAME` (optional) :: The username to
use to authenticate to the SMTP server.

`EVENTLINE_NOTIFICATIONS_SMPT_SERVER_PASSWORD` (optional) :: The password to
use to authenticate to the SMTP server.

`EVENTLINE_NOTIFICATIONS_FROM_ADDRESS` (optional) :: The email address to use in the
`From` header field.

`EVENTLINE_NOTIFICATIONS_SUBJECT_PREFIX` (optional) :: A character string to
use as prefix for the `Subject` header field.

`EVENTLINE_NOTIFICATIONS_SIGNATURE` :: A character string to insert as
signature at the end of all emails.

See the <<configuration-specification,configuration specification>> for more
information about settings.

===== Building your own image

The `exograd/eventline` is provided for convenience. For production use, it is
advised to build your own image. This allows you to follow the conventions
used by your organization and gives you total control on the base system,
environment and configuration.

Feel free to start from the default
https://github.com/exograd/eventline/blob/master/Dockerfile[Dockerfile] or to
write your own from scratch.

==== Helm chart

_Coming soon._

=== Configuration

==== Configuration file

Eventline uses a configuration file whose path is provided with the `-c`
command line option.

CAUTION: The configuration file contains the global encryption key used to
secure storage of sensitive information in the database. You must make sure
that the UNIX user executing Eventline is the only user able to read the
configuration file. Alternatively, you can use templating and environment
variables to provide sensitive settings.

==== Templating

The configuration file is treated as a template using the
https://pkg.go.dev/text/template[Go template format]. Templating currently
supports the following functions:

`env <name>` :: Return the value of the `<name>` environment variable.

.Example:
[source,yaml]
----
data_directory: "/usr/share/eventline"

encryption_key: {{ env "EVENTLINE_ENCRYPTION_KEY" }}

pg:
  uri: {{ env "EVENTLINE_PG_URI" }}
----

At startup, Eventline loads the configuration file, renders it and then parses
it as a YAML document.

[#configuration-specification]
==== Specification

A configuration file is an object containing the following fields:

`logger` (optional object) :: The configuration of the logger used to print
information and errors. The default value is:
+
[source,yaml]
----
backend_type: "terminal"
backend:
  color: true
  domain_width: 32
----

`data_directory` (optional string, default to `data`) :: The path of the
directory containing Eventline data files.

`api_http_server` (optional object) :: the HTTP server configuration of the
API interface. The default value is:
+
[source,yaml]
----
address: "localhost:8085"
----

`web_http_server` (optional object) :: the HTTP server configuration of the
web interface. The default value is:
+
[source,yaml]
----
address: "localhost:8087"
----

`pg` (optional object) :: The configuration of the PostgreSQL server.

`encryption_key` (string) :: The global encryption key used to encrypt
sensitive information in the database. The key must be a 32 byte AES key
encoded using https://en.wikipedia.org/wiki/Base64[Base64]. You can generate a
key using OpenSSL:
+
----
openssl rand -base64 32
----

`web_http_server_uri` (optional string, default to `http://localhost:8087`) ::
The URI which can be used to access the Eventline web interface from outside
of the server. This URI will be used to generate webhook URIs among other
thing.

`connectors` (optional object) :: The configuration of each connector. Refer
to the connector documentation for the settings available for each connector.

`max_parallel_job_executions` (optional integer) :: If set, the maximum number
of jobs which can run in parallel for the entire platform.

`job_execution_retention` (optional integer) :: If set, a number of days after
which old job executions will be deleted. Note that changing this setting will
not affect job executions which have already been terminated.

`session_retention` (optional integer) :: If set, a number of days after which
sessions will be deleted.

`runners` (optional object) :: The configuration of each runner. Refer to the
<<chapter-runners,runner documentation>> for the settings available for each
runner.

`notifications` (optional object) :: The configuration of the email
notification system. The default value is:
+
[source,yaml]
----
smtp_server:
  address: "localhost:25"
from_address: "no-reply@localhost"
subject_prefix: "[eventline] "
signature: "This email is a notification sent by the Eventline job scheduling software."
----

===== HTTP server specification

The configuration of a HTTP server is an object containing the following
fields:

`address` (optional string, default to `localhost:8080`) :: The address to
listen on as a `<host>:<port>` string.

`tls` (optional object) :: If set, use TLS for the connection. The object
contains the following fields:

    `certificate` (string) ::: The path of the TLS certificate file.

    `private_key` (string) ::: The path of the TLS private key.

===== PostgreSQL specification

The configuration of the PostgreSQL server is an object containing the
following fields:

`uri` (optional string) :: The URI of the PostgreSQL server. The default value
is `postgres://eventline:eventline@localhost:5432/eventline`.

===== Notifications specification

The configuration for the notification system is an object containing the
following fields:

`smtp_server` (optional object) :: The configuration of the SMTP server to use
when sending emails.

`from_address` (optional string) :: The email address to use in the `From`
header field.

`subject_prefix` (optional string) :: A character string to use as prefix for
the `Subject` header field.

`signature` (optional string) :: A character string to insert as signature at
the end of all emails.

`allowed_domains` (optional string array) :: A list of domains which can used
in notification email addresses. If the array is empty, all domains are
allowed.

TIP: the `allowed_domains` setting is useful to make sure you that all
notifications are sent to email addresses you control: this way you can limit
the chances of losing notifications due to a mistake, and you guarantee that
you will not send emails to someone out of your organization.

===== SMTP server specification

The configuration of the SMTP server is an object containing the following
fields:

`address` (optional string, default to `localhost:25` :: The address of the
server using the `<host>:<port>` format.

`username` (optional string) :: The username to use for authentication.

`password` (optional string) :: The password to use for authentication.
