[#chapter-runners]
== Runners

Eventline has the ability to run jobs in different environments using runners.
Each job can select the runner to use for execution and its parameters.

CAUTION: Running job in an environment means that sensible data can be stored
and accessed during execution. Make sure to take into account users and
programs who can access system when they are executing Eventline jobs.

The default runner is the most basic one, the local runner.

=== `local`

The `local` runner executes jobs directly on the machine where Eventline is
hosted.

Its bigger advantage is how fast it is: since there is no intermediary
execution layer, it lets you execute jobs in a couple milliseconds.

Using the `local` runner is also useful for jobs containing lower level tasks
that could be difficult to run in a virtualized environment.

.Example
[source,yaml]
----
runner:
  name: "local"
----

Note that the `local` runner being the default runner, jobs using it do not need
to include a `runner` field.

==== Configuration

The `local` runner supports the following settings:

`root_directory` (optional string, default to `/tmp/eventline/execution`) ::
The directory used to store temporary data during the execution of each job.
The path must be absolute.

==== Parameters

There are no parameters for jobs using the `local` runner.

==== Identity

The `local` runner does not use any identity.

=== `docker`

The `docker` runner executes jobs in containers executed by the
https://www.docker.com[Docker daemon]. All the steps in a job are executed
sequentially in the same container.

.Example
[source,yaml]
----
runner:
  name: "docker"
  parameters:
    image: "alpine:3.16"
    cpu_limit: 2.0
    memory_limit: 1000
----

==== Configuration

The `docker` runner supports the following settings:

`uri` (optional string) :: The URI of the Docker HTTP endpoint. If set,
Eventline will connect to the Docker daemon in TCP mode instead of using the
local UNIX socket.

`ca_certificate_path` (optional string) :: The path of the CA certificate file
to use to connect to the Docker daemon.

`certificate_path` (optional string) :: The path of the certificate file to
use to connect to the Docker daemon.

`private_key_path` (optional string) :: The path of the private key file to
use to connect to the Docker daemon.

WARNING: Using HTTP to connect to the Docker daemon is experimental; it is not
recommended for security reasons.

==== Parameters

Jobs using the `docker` runner support the following parameters:

`image` (string) :: The reference of the image to use for the container.

`cpu_limit` (optional number) :: Set a limit to the number of virtual CPUs
that can be used during execution.

`memory_limit` (optional integer) :: Set a limit to the amount of memory in
megabytes that can be used during execution.

==== Identity

_TODO_

=== `ssh`

The `ssh` runner uses the https://en.wikipedia.org/wiki/Secure_Shell[Secure
Shell Protocol] to execute the job on a remote server.

.Example
[source,yaml]
----
runner:
  name: "ssh"
  parameters:
    host: "my-server.example.com"
    user: "my-user"
  identity: "my-ssh-key"
----

==== OpenSSH server configuration

The OpenSSH server does not let clients set arbitrary environment variables.
In order to be able to run Eventline jobs on a server, edit the SSH daemon
configuration file at `/etc/ssh/sshd_config` and add the following setting:

----
AcceptEnv EVENTLINE EVENTLINE_*
----

Do not forget to restart the SSH daemon.

WARNING: If this setting is not added, jobs using the `ssh` runner will fail
with the `ssh: setenv failed` error message.

==== Configuration

The `ssh` runner supports the following settings:

`root_directory` (optional string, default to `/tmp/eventline/execution`) ::
The directory used to store temporary data during the execution of each job on
the remote server. The path must be absolute.

==== Parameters

Jobs using the `ssh` runner support the following parameter:

`host` (string) :: The hostname or IP address of the server to connect to.

`port` (optional integer, default to 22) :: The port number to use.

`user` (optional string, default to `root`) :: The user to connect as.

`host_key` (optional string) :: The expected host key of the server as a
public key encoded using Base64.

`host_key_algorithm` (optional string) :: The algorithm of the host key if
`host_key` is provided. Must be one of `ssh-dss`, `ssh-rsa`,
`ecdsa-sha2-nistp256`, `ecdsa-sha2-nistp384`, `ecdsa-sha2-nistp521` and
`ssh-ed25519`

TIP: You can obtain the host key of a remote server using `ssh-keyscan`.

==== Identity

The following identities can be used with the runner:

`generic/password` :: Authenticate using the password in the identity.
The `login` field is ignored.

`generic/ssh_key` :: Authenticate using the private key in the identity.

=== `kubernetes`

The `kubernetes` runner executes jobs in a https://kubernetes.io[Kubernetes
cluster]. All the steps in a job are executed sequentially in the same
container of the same pod.

.Example
[source,yaml]
----
runner:
  name: "kubernetes"
  parameters:
    image: "alpine:3.16"
    namespace: "eventline"
----

NOTE: The `kubernetes` runner is only available in Eventline Pro.

==== Configuration

The `kubernetes` runner supports the following settings:

`config_path` (optional string) :: The path of the
https://kubernetes.io/docs/concepts/configuration/organize-cluster-access-kubeconfig[kubeconfig]
file to use to connect to the cluster. If not set, Eventline will either use
the value of the `KUBECONFIG` environment variable if it set or
`$HOME/.kube/config` otherwise.

`namespace` (optional string, default to `default`) :: The namespace to create
pods into.

==== Parameters

Jobs using the `kubernetes` runner support the following parameters:

`image` (string) :: The reference of the image to use for the container.

`namespace` (optional string) :: The namespace to create the pod into. If not
set, the runner uses the namespace defined in the configuration.

==== Identity

_TODO_
