== Writing jobs

=== Definition files

Jobs are defined in YAML documents. Each file contains a single object, the
job specification. When you deploy one of these files, Eventline uses the
`name` field to either create a new job or update an existing one.

NOTE: While job filenames have no particular meaning to Eventline, using the
name of the job as filename is helpful when organizing multiple job files.

=== Deployment

Jobs are deployed using Evcli. The `deploy-job` command deploys a single job
file, while `deploy-jobs` can be used to deploy multiple jobs at the same
time.

Both commands accept the `--dry-run` (or `-n`) option which validate job files
without actually deploying them.

TIP: While you can write and deploy jobs manually, you will probably reach a
point where you want to organize all your jobs in a central place with version
control. In that case, you could use a job which calls evcli to deploy all
jobs in the repository, and trigger it on new commits.

=== Export

Jobs can be exported out of Eventline at any time using Evcli and the
`export-job` command. The job is exported as a job specification file which
can then be edited and re-deployed.

=== Writing code

Jobs contain a list of steps. Each steps is executed as a small independent
program. There are several ways to define each step, each one with its pros
and cons.

==== Code blocks

Code blocks let you write code inline.

.Example
[source,yaml]
----
name: "code-blocks"
steps:
  - code: |
      echo "Hello world!"
  - code: |
      #!/usr/bin/env ruby

      puts "Use the language of your choice."
----

The first code block does not start with a
https://en.wikipedia.org/wiki/Shebang_(Unix)[shebang line], so Eventline
automatically inserts the default project header which contains the
`#!/bin/sh` shebang line.

In the second block, we provide the shebang line ourselves, and write the code
in Ruby.

==== Commands

Commands are a simple way to execute a program with or without arguments.

.Example
[source,yaml]
----
name: "command"
steps:
  - command:
      name: "ls"
      arguments: ["-l", "/tmp"]
----

Here we simply execute the `ls` program with two arguments.

==== Scripts

Scripts give you the ability to use files written out of the job definition
file. This is particularly nice when you have to write more than a couple
lines of code, and want to edit the code properly instead of writing inline
YAML content.

.Example
[source,yaml]
----
name: "script"
steps:
  - script:
      path: "utils/generate-report.rb"
      arguments: ["--output", "/tmp/report.pdf"]
----

In this example, the actual code is written in the `utils/generate-report.rb`
file. We instruct Eventline to use this code during execution with the
provided arguments.

During deployment, Eventline reads script files and embeds their content in the
job specification structure as if it had been written inline.

Even better, if the job is exported later, Evcli will recreate the original
script file as you would expect.

=== Reference

[#job-specification]
==== Job specification

A job is an object containing the following fields:

`name` (string) ::
The name of the job.

`description` (optional string) :: A textual description of the job.

`trigger` (optional object) :: The specification of a trigger indicating when
to execute the job.

`parameters` (optional object array) :: A list of parameter specifications
used to execute the job manually.

`runner` (optional object) :: The specification of the runner used to execute
the job.

`concurrent` (optional boolean, default to `false`) :: Whether to allow
concurrent executions for this job or not.

`retention` (optional integer) :: The number of days after which past
executions of this job will be deleted. This value override the global
`job_retention` setting.

`identities` (optional string array) :: The names of the identities to inject
during job execution.

`environment` (optional object) :: A set of environment variables mapping
names to values to be defined during job execution.

`steps` (object array) :: A list of steps which will be executed sequentially.

[#trigger-spec]
==== Trigger specification

A trigger is an object containing the following fields:

`event` (string) :: The event to react to formatted as `<connector>/<event>`.

`parameters` (optional object) :: The set of parameters associated to the
event. Refer to the connector documentation to know which parameters are
available for each event.

`identity` (optional string) :: The name of an identity to use for events
which require authentication. For example the `github/push` event needs an
identity to create the GitHub hook used to listen to push events.

`filters` (optional object array) :: A list of filters used to control whether
an event matches the trigger or not.

==== Parameter specification

A parameter is an object containing the following fields:

`name` (string) :: The name of the parameter.

`description` (optional string) :: A textual description of the parameter.

`type` (string) :: The type of the parameter. The following types are
supported:

    `number` ::: Either an integer or an IEEE 754 double precision floating point
    value.
    `integer` ::: An integer.
    `string` ::: A character string.
    `boolean` ::: A boolean.

`values` (optional string array) :: For parameters of type `string`, the list
of valid values.

`default` (optional value) :: The default value of the parameter. The type of
the field must be compatible with the type of the parameter.

`environment` (optional string) :: The name of an environment variable to be
used to inject the value of this parameter during execution.

==== Filter specification

Each filter is an object made of a path and zero or more predicates. The path
is a JSON pointer (see
https://datatracker.ietf.org/doc/html/rfc6901[RFC 6901]) applied to the data
of the event.

Predicates are additional members which are applied to the value referenced by
the path. An event matches a filter if all predicates are true.

The following predicates are supported:

`is_equal_to` (optional value) :: Matches if the value referenced by the path
is equal to the value associated with the predicate.

`is_not_equal_to` (optional value) :: Matches if the value referenced by the
path is different from the value associated with the predicate.

`matches` (optional value) :: The associated value is a regular expression;
the predicate matches if the value referenced by the path is a string which
matches this regular expression. Eventline supports the
https://github.com/google/re2/wiki/Syntax[RE2] syntax.

`does_not_match` (optional value) :: The associated value is a regular
expression; the predicate matches if the value referenced by the path is a
string which does not match this regular expression.

.Example
[source,yaml]
----
filters:
  - path: "/branch"
    matches: "^feature-"
  - path: "/repository"
    is_not_equal_to: "tests"
----

When applied to a `github/push` event, this filters will match push events on
branches whose name starts with `feature-` but not if the repository is named
`tests`.

[#runner-specification]
==== Runner specification

A runner is an object containing the following fields:

`name` (string) :: The name of the runner.

`parameters` (optional object) :: The set of parameters associated to the
runner. Refer to the runner documentation to know which parameters are
available for each runner.

`identity` (optional string) :: The name of an identity to use for
authentication purposes associated with the runner. Refer to the runner
documentation to know which identities can be used for each runner.

==== Step specification

A step is an object containing the following fields:

`label` (optional string) :: A short description of the step which will be
displayed on the web interface.

`code` (optional string) :: The fragment of code to execute for this step.

`command` (optional object) :: The command to execute for this step. Contains
the following members:
    `name` (string) ::: The name of the command.
    `arguments` (optional string array) ::: The list of arguments to pass to
    the command.

`script` (optional object) :: An external script to execute for this step.
Contains the following members:
    `path` (string) ::: The path of the script file relative to the job file.
    `arguments` (optional string array) ::: The list of arguments to pass to
    the script.

Each step must contain a single field among `code`, `command` and `script`
indicating what will be executed.
