#!/bin/sh

# PROVIDE: eventline
# REQUIRE: DAEMON
# KEYWORD: shutdown

. /etc/rc.subr

name="eventline"

rcvar="eventline_enable"

: ${eventline_enable:="no"}
: ${eventline_cfg_path:="/usr/local/etc/eventline/eventline.yaml"}
: ${eventline_syslog_tag:="eventline"}

procname="daemon"
pidfile="/var/run/eventline/$name.pid"

command="/usr/sbin/daemon"
command_args="-P $pidfile -u $name -T $eventline_syslog_tag -R 5 /usr/local/bin/eventline -c $eventline_cfg_path"

required_files="$eventline_cfg_path"

start_precmd="eventline_precmd"

eventline_precmd() {
    install -d -o eventline /var/run/eventline/
}

load_rc_config $name
run_rc_command "$1"
