#!/bin/sh

# PROVIDE: eventline
# REQUIRE: DAEMON
# KEYWORD: shutdown

. /etc/rc.subr

name="eventline"
rcvar="eventline_enable"
load_rc_config $name

: ${eventline_enable:="no"}
: ${eventline_user:="eventline"}
: ${eventline_cfg_path:="/usr/local/etc/eventline/eventline.yaml"}
: ${eventline_syslog_tag:="eventline"}

command="/usr/sbin/daemon"
procname="/usr/local/bin/eventline"
pidfile="/var/run/$name.pid"

start_cmd="${name}_start"

eventline_start() {
    echo "Starting $name..."                        \
    /usr/sbin/daemon                                \
        -R 5                                        \
        -p $pidfile                                 \
        -u $eventline_user                          \
        -T $eventline_syslog_tag                    \
        /usr/local/bin/$name -c $eventline_cfg_path
}

run_rc_command "$1"
